import os
Import('region_band_list')

# get current directory
# cwd = os.getcwd()
cwd = os.path.dirname(File('SConscript').rfile().abspath)

# The set of source files associated with this SConscript file.
src = Glob('*.c') 
src += Glob('soft-se/*.c') 
src_tmp = Split("""
region/Region.c
region/RegionCommon.c
region/RegionBaseUS.c
""")
src += File(src_tmp)

for band in region_band_list:
    tmp = Glob('region/Region' + band.split('_')[1] + '.c')
    src.append(tmp[0])
    if band == 'REGION_CN470':
        src.append(Glob('region/RegionCN470A20.c'))
        src.append(Glob('region/RegionCN470B20.c'))
        src.append(Glob('region/RegionCN470A26.c'))
        src.append(Glob('region/RegionCN470B26.c'))

cpppath = [
    cwd,
    cwd + '/soft-se',
    cwd + '/region']

cppdefines = []

group = {
    'SOURCE'     : src,
    'CPPDEFINES' : cppdefines,
    'CPPPATH'    : cpppath}

Return('group')
