import os

# get current directory
# cwd = os.getcwd()
cwd = os.path.dirname(File('SConscript').rfile().abspath)

# The set of source files associated with this SConscript file.
src = Glob('*.c') 
src_tmp = Glob('gcc/*.s')
if len(src_tmp) == 1:
    src += src_tmp
else:
    print('Error too many *.s!!!')

cpppath = [
    cwd,
    cwd + '/../']

cppdefines = []

# print(cpppath)

group = {
    'SOURCE'     : src,
    'CPPDEFINES' : cppdefines,
    'CPPPATH'    : cpppath}

Return('group')
