import os
import glob

Import('SCON_PROJECT_NAME')
# get current directory
# cwd = os.getcwd()
cwd = os.path.dirname(File('SConscript').rfile().abspath)

# The set of source files associated with this SConscript file.
# src_tmp = glob.glob(cwd + f'/demo/{SCON_PROJECT_NAME.upper()}/*.c')
src_tmp = Glob(f'demo/{SCON_PROJECT_NAME.upper()}/*.c')
src_tmp += Glob('common/*.c')
src = File(src_tmp)

cpppath = [
    cwd + '/common',
    cwd + f'/demo/{SCON_PROJECT_NAME.upper()}'
]

cppdefines = []

group = {
    'SOURCE'     : src,
    'CPPDEFINES' : cppdefines,
    'CPPPATH'    : cpppath}

Return('group')
